---
name: scaffold working directory
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'target'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TFACTION_TARGET: ${{github.event.inputs.target}}
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - uses: aquaproj/aqua-installer@a34cc75221784a96e3caf4bbf716ff67a160a3f1 # v1.0.0
        with:
          aqua_version: v1.17.1

      - uses: ./scaffold-working-dir
        id: scaffold-working-dir

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: ./create-scaffold-pr
        with:
          github_app_token: ${{ steps.generate_token.outputs.token }}
