name: test-get-target-config

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
    - uses: aquaproj/aqua-installer@a34cc75221784a96e3caf4bbf716ff67a160a3f1 # v1.0.0
      with:
        aqua_version: v1.17.1
    - uses: ./get-target-config
      id: target-config
      env:
        TFACTION_CONFIG: get-target-config/tests/config-1.yaml
        TFACTION_TARGET: aws/foo
        TFACTION_IA_APPLY: 'false'
        TFACTION_JOB_TYPE: 'terraform'
    - run: echo "${{ steps.target-config.outputs.working_directory }}"
    - run: echo "${{ steps.target-config.outputs.aws_assume_role_arn }}"
    - run: echo "${{ steps.target-config.outputs.aws_region }}"
    - run: echo "${{ steps.target-config.outputs.s3_bucket_name_plan_file }}"
    - run: echo "${{ steps.target-config.outputs.s3_bucket_name_tfmigrate_history }}"
    - run: echo "${{ steps.target-config.outputs.template_dir }}"
